import { useTheme } from "./useTheme";
import { buildTheme, type ThemeSpec } from "~/theme/build";
import { resolveTheme } from "~/theme/library";
import type { ThemeDefinition, ThemeScheme } from "~/theme/roles";
import {
  addAgentToProject,
  createAgent,
  deleteAgent,
  selectAgent,
  updateAgent,
  type AgentDraft,
  type AgentEdit,
  type FacePaint,
} from "~/utils/agents";
import { hydratePresets } from "~/utils/presetStore";
import { useStripPrefs } from "./useStripPrefs";
import { usePaneWidthPrefs } from "./usePaneWidthPrefs";
import { CENTER_MODES } from "~/utils/stripScroll";
import type { AgentModelRef, ProviderKind, RuntimeEvent } from "~/types/desktop";
import type { PaneKind } from "~/types/studio";

// The receiving end of the app gateway's steering tools. An agent's tool call
// runs in the main process, where none of this state lives: the theme library,
// the agent roster and the thread strip's settings are all the renderer's, so
// each write arrives here as a runtime event and is applied through the very
// same functions the settings panes call.
//
// That last part is the point. Nothing below re-implements a rule — what a
// cleared field on a built-in agent falls back to, what a nameless preset is
// refused for, how wide a rung is — because every one of those already has one
// answer, and a second copy here would be the one that drifts.

let isListening = false;
let unsubscribe: (() => void) | null = null;

const PROVIDERS = new Set<ProviderKind>([
  "codex",
  "claudeAgent",
  "cursor",
  "opencode",
  "droid",
  "antigravity",
]);

/** A model ref off the wire, or null if it names no model this build can run.
 *  The gateway validates the provider against the same list, so this is the
 *  guard for a shell of a different vintage than the window it is talking to. */
function readModelRef(
  value: { provider: string; model: string; label?: string } | undefined,
): AgentModelRef | null {
  if (!value) return null;
  const provider = value.provider.trim();
  const model = value.model.trim();
  // SAFETY: `has` only reads the set; the value is a ProviderKind exactly when
  // this returns true, which is what the branch below relies on.
  if (!model || !PROVIDERS.has(provider as ProviderKind)) return null;
  // SAFETY: guarded by the membership check immediately above.
  const ref: AgentModelRef = { provider: provider as ProviderKind, model };
  const label = value.label?.trim();
  if (label) ref.label = label;
  return ref;
}

/** A face off the wire, or null if either colour is missing. Both halves move
 *  together: repainting the marble and leaving the old ink on it is how a face
 *  goes unreadable. */
function readFace(value: { body: string; ink: string } | undefined): FacePaint | null {
  if (!value) return null;
  const body = value.body.trim();
  const ink = value.ink.trim();
  if (!body || !ink) return null;
  return { body, ink };
}

/** Apply one theme mutation: a custom theme to register, a preview to show or
 *  discard, or a saved theme/mode change. */
function applyThemeMutation(
  event: Extract<RuntimeEvent, { type: "app.theme_mutation" }>,
): void {
  const { setTheme, setMode, previewTheme, cancelPreview, saveCustomTheme, theme } = useTheme();

  // 1. Custom theme creation and registration
  if (event.customTheme) {
    const ct = event.customTheme;
    const isAdaptive = ct.appearance === "adaptive";
    let spec: ThemeSpec;

    if (isAdaptive) {
      spec = {
        id: ct.id,
        label: ct.label,
        blurb: ct.blurb ?? "Custom theme generated by assistant.",
        kind: "adaptive",
        light: {
          ground: ct.ground ?? "#f6f5f3",
          accent: ct.accent,
          roles: ct.roles,
        },
        dark: {
          ground: ct.ground ?? "#0f1115",
          accent: ct.accent,
          roles: ct.roles,
        },
      };
    } else {
      const appScheme: ThemeScheme = ct.appearance === "light" ? "light" : "dark";
      spec = {
        id: ct.id,
        label: ct.label,
        blurb: ct.blurb ?? "Custom theme generated by assistant.",
        kind: "fixed",
        appearance: appScheme,
        palette: {
          ground: ct.ground ?? (appScheme === "light" ? "#f6f5f3" : "#0f1115"),
          accent: ct.accent,
          roles: ct.roles,
        },
      };
    }

    saveCustomTheme(spec);
    return;
  }

  // 2. Discarding an active preview
  if (event.preview === false) {
    cancelPreview();
    return;
  }

  // 3. Live non-destructive preview override
  if (event.preview === true) {
    const baseTheme: ThemeDefinition = event.themeId
      ? resolveTheme(event.themeId)
      : theme.value;

    if (event.colors && Object.keys(event.colors).length > 0) {
      const previewSpec: ThemeSpec = {
        id: `preview-${baseTheme.id}`,
        label: `Preview (${baseTheme.label})`,
        blurb: "Temporary preview override.",
        kind: "fixed",
        appearance: baseTheme.appearance,
        palette: {
          ground: event.colors.ground ?? baseTheme.colors[baseTheme.appearance]?.ground ?? "#0f1115",
          accent: event.colors.accent ?? baseTheme.colors[baseTheme.appearance]?.accent ?? "#f97316",
          roles: event.colors,
        },
      };
      const builtPreview = buildTheme(previewSpec);
      // SAFETY: event.mode is validated by schema as "dark" | "light" | "system".
      const previewScheme = (event.mode === "light" || event.mode === "dark" ? event.mode : null) as ThemeScheme | null;
      previewTheme(builtPreview, previewScheme);
    } else {
      // SAFETY: event.mode is validated by schema as "dark" | "light" | "system".
      const previewScheme = (event.mode === "light" || event.mode === "dark" ? event.mode : null) as ThemeScheme | null;
      previewTheme(baseTheme, previewScheme);
    }
    return;
  }

  // 4. Standard persistent theme & mode mutation
  if (event.themeId) {
    // resolveTheme falls back to kone for an id the library doesn't hold, so
    // storing the requested id unchecked would persist a preference that
    // silently renders as something else on every later boot. The gateway
    // resolves against its own catalog before emitting; this is the guard for
    // the case where the two have drifted apart.
    const resolved = resolveTheme(event.themeId);
    if (resolved.id === event.themeId) {
      setTheme(event.themeId);
    } else {
      console.warn(
        `[kone] Ignoring theme mutation for unknown theme "${event.themeId}".`,
      );
    }
  }
  if (event.mode) {
    setMode(event.mode);
  }
}

/**
 * Apply one roster mutation.
 *
 * Every branch goes through `~/utils/agents`, which is where an agent's
 * inheritance is resolved — a cleared field on a built-in hands back to the
 * shipped preset, and on a user-made agent unsets. The gateway deliberately
 * knows none of that, so this must not either.
 */
async function applyAgentMutation(
  event: Extract<RuntimeEvent, { type: "app.agent_mutation" }>,
): Promise<void> {
  if (event.op === "select") {
    // No agent named is a real choice, not a missing one: the next turn runs as
    // a guest, which is what kone ships.
    selectAgent(event.agentId ?? null);
    return;
  }

  if (event.op === "delete") {
    if (event.agentId) await deleteAgent(event.agentId);
    return;
  }

  if (event.op === "create") {
    const name = event.fields?.name?.trim();
    // A nameless agent has nothing to be called, so there is nothing to make.
    if (!name) return;
    const draft: AgentDraft = { name };
    // The gateway minted the id so it could report the agent it made; honouring
    // it is what makes that report true.
    if (event.agentId) draft.id = event.agentId;
    const role = event.fields?.role?.trim();
    if (role) draft.role = role;
    const instructions = event.fields?.instructions?.trim();
    if (instructions) draft.instructions = instructions;
    const face = readFace(event.fields?.face);
    if (face) draft.face = face;
    const model = readModelRef(event.fields?.model);
    if (model) draft.model = model;

    const created = await createAgent(draft);
    if (created && event.projectPath) await addAgentToProject(event.projectPath, created.id);
    return;
  }

  if (!event.agentId) return;
  const edit: AgentEdit = {};
  const name = event.fields?.name?.trim();
  if (name) edit.name = name;
  if (event.fields?.role !== undefined) edit.role = event.fields.role;
  if (event.fields?.instructions !== undefined) edit.instructions = event.fields.instructions;
  const face = readFace(event.fields?.face);
  if (face) edit.face = face;
  const model = readModelRef(event.fields?.model);
  if (model) edit.model = model;
  // A clear is spelled as a name on a list rather than a null across the wire,
  // because a null there cannot be told from a client filling in the blanks.
  // Here, at the end, it becomes the null the edit means.
  for (const field of event.clear ?? []) edit[field] = null;

  await updateAgent(event.agentId, edit);
}

/** Apply one thread strip mutation. A setting the event doesn't name is left
 *  alone, the same contract the theme mutation follows. */
function applyStripMutation(
  event: Extract<RuntimeEvent, { type: "app.strip_mutation" }>,
): void {
  if (event.centering) {
    const { centerMode } = useStripPrefs();
    // Checked against the modes that exist rather than trusted: the gateway
    // validates too, but a mode the board doesn't implement would leave the
    // strip obeying nothing.
    const known = CENTER_MODES.find((mode) => mode.value === event.centering);
    if (known) centerMode.value = known.value;
  }

  if (event.defaultWidths) {
    const { setDefaultWidth } = usePaneWidthPrefs();
    // setDefaultWidth clamps to the ladder, so a rung past the end lands on the
    // widest rather than on a width the board cannot lay out.
    for (const [kind, rung] of Object.entries(event.defaultWidths)) {
      if (rung === undefined) continue;
      // SAFETY: the event's `defaultWidths` is declared with exactly the
      // PaneKind keys, so an entry key is one of them.
      setDefaultWidth(kind as PaneKind, rung);
    }
  }
}

/**
 * Initialize reactive steering handlers that connect runtime desktop events
 * (from the MCP gateway over IPC) to the web application's reactive state.
 */
export function initAppSteering(): () => void {
  if (isListening) {
    return () => {
      /* already bound */
    };
  }

  const bridge = window.koneDesktop;
  if (!bridge?.agent?.onEvent) {
    return () => {
      /* no desktop bridge in standalone web mode */
    };
  }

  unsubscribe = bridge.agent.onEvent((event) => {
    if (event.type === "app.theme_mutation") {
      applyThemeMutation(event);
      return;
    }
    if (event.type === "app.agent_mutation") {
      void applyAgentMutation(event);
      return;
    }
    if (event.type === "app.subagent_presets_changed") {
      // The gateway already wrote the row — it owns the same store this reads
      // through — so there is nothing to apply, only to re-read. Re-reading
      // rather than patching the cache in place is what keeps the sort order and
      // the store's own clamping intact.
      void hydratePresets();
      return;
    }
    if (event.type === "app.strip_mutation") {
      applyStripMutation(event);
    }
  });

  isListening = true;

  return () => {
    if (unsubscribe) {
      unsubscribe();
      unsubscribe = null;
    }
    isListening = false;
  };
}

export function useAppSteering() {
  return {
    initAppSteering,
  };
}
