import { describe, expect, it } from "bun:test";
import type { RuntimeEvent } from "../../types.js";
import { createRegistry } from "../registry.js";
import type { GatewayToolContext } from "../registry.js";
import {
  colourWords,
  createAppThemeTools,
  filterThemes,
  resolveTheme,
  type AppearanceReading,
  type CurrentThemeState,
  type ThemeRosterEntry,
} from "./appTheme.js";

function makeCtx(overrides: Partial<GatewayToolContext> = {}): GatewayToolContext {
  return {
    threadId: "thread-test-1",
    turnId: "turn-test-1",
    provider: "claudeAgent",
    model: "claude-3-7-sonnet",
    cwd: process.cwd(),
    requestId: "req-1",
    ...overrides,
  };
}

function entry(overrides: Partial<ThemeRosterEntry> & Pick<ThemeRosterEntry, "id">): ThemeRosterEntry {
  return {
    label: overrides.id,
    blurb: "",
    kind: "fixed",
    appearance: "dark",
    schemes: [overrides.appearance ?? "dark"],
    accent: "#888888",
    ground: "#111111",
    origin: "built-in",
    ...overrides,
  };
}

/** A stand-in for what the renderer reports: a few built-ins, one import, one
 *  user-authored theme. The last two are the point of the roster — nothing in
 *  this package could know they exist. */
const ROSTER: readonly ThemeRosterEntry[] = [
  entry({
    id: "kone",
    label: "kone",
    blurb: "The app's own appearance. Follows your system light and dark.",
    kind: "adaptive",
    appearance: "light",
    schemes: ["light", "dark"],
    accent: "#d97757",
    ground: "#f6f5f3",
  }),
  entry({
    id: "t3chat",
    label: "T3 Chat",
    blurb: "Pink paper and plum night, one magenta voice.",
    kind: "adaptive",
    appearance: "light",
    schemes: ["light", "dark"],
    accent: "#cf1f6d",
    ground: "#fbf1fa",
  }),
  entry({
    id: "grove",
    label: "Grove",
    blurb: "Forest and copper, morning paper and night undergrowth.",
    kind: "adaptive",
    appearance: "light",
    schemes: ["light", "dark"],
    accent: "#2f6b38",
    ground: "#f4f5f1",
  }),
  entry({
    id: "nocturne",
    label: "Nocturne",
    blurb: "Violet-black night shift. Amber for warmth, cyan for anything live.",
    accent: "#a78bfa",
    ground: "#0f1018",
  }),
  entry({
    id: "press",
    label: "Press",
    blurb: "A print room after hours. Neutral stone furniture; all the colour is in the ink.",
    accent: "#ef6398",
    ground: "#101214",
  }),
  entry({
    id: "dracula",
    label: "Dracula",
    blurb: "Imported from a VS Code colour theme.",
    accent: "#bd93f9",
    ground: "#282a36",
    origin: "imported",
  }),
  entry({
    id: "brand-indigo",
    label: "Brand Indigo",
    blurb: "Custom theme generated by assistant.",
    accent: "#6366f1",
    ground: "#0f172a",
    origin: "custom",
  }),
];

const rosterTools = (extra: Parameters<typeof createAppThemeTools>[0] = {}) =>
  createAppThemeTools({ readThemes: () => ROSTER, ...extra });

describe("appTheme tools", () => {
  describe("colour vocabulary", () => {
    it("names an accent's hue so a theme answers to the word for its colour", () => {
      expect(colourWords("#2f6b38")).toContain("green");
      expect(colourWords("#a78bfa")).toContain("purple");
      expect(colourWords("#526fff")).toContain("blue");
      expect(colourWords("#c45228")).toContain("orange");
      expect(colourWords("#ef6398")).toContain("pink");
      expect(colourWords("#c026d3")).toContain("magenta");
    });

    // A near-grey has a hue angle, but honouring it would file a stone-coloured
    // theme under whichever colour it happens to lean a fraction towards.
    it("describes a near-grey by its neutrality rather than its hue", () => {
      expect(colourWords("#8a8a8c")).toEqual(["neutral", "grey", "gray", "mono"]);
    });

    // A role may legitimately hold a relational value instead of a literal.
    it("contributes no words for a value that isn't a colour", () => {
      expect(colourWords("var(--ground)")).toEqual([]);
    });
  });

  describe("theme resolver and filtering", () => {
    it("resolves exact ids and labels, punctuation aside", () => {
      expect(resolveTheme("kone", ROSTER)?.id).toBe("kone");
      expect(resolveTheme("t3 chat", ROSTER)?.id).toBe("t3chat");
      expect(resolveTheme("Nocturne", ROSTER)?.id).toBe("nocturne");
    });

    // The whole reason the roster is reported rather than compiled in.
    it("resolves imported and user-authored themes", () => {
      expect(resolveTheme("dracula", ROSTER)?.origin).toBe("imported");
      expect(resolveTheme("brand indigo", ROSTER)?.origin).toBe("custom");
    });

    it("resolves a colour word to a theme with that accent", () => {
      expect(resolveTheme("green", ROSTER)?.id).toBe("grove");
      expect(resolveTheme("purple", ROSTER)?.id).toBe("nocturne");
    });

    // The description carries the words nobody tagged: "forest" is in Grove's
    // blurb and nowhere else.
    it("falls back to the theme's own description", () => {
      expect(resolveTheme("forest", ROSTER)?.id).toBe("grove");
    });

    // An exact name has to beat another theme merely described in those words:
    // Press is "a print room", but a theme actually called Press wins.
    it("prefers an exact name over a description that mentions it", () => {
      const roster = [
        entry({ id: "atelier", label: "Atelier", blurb: "A press room after hours." }),
        ...ROSTER,
      ];
      expect(resolveTheme("press", roster)?.id).toBe("press");
    });

    it("resolves nothing for a theme the library does not hold", () => {
      expect(resolveTheme("nonexistent-fantasy-theme", ROSTER)).toBeUndefined();
    });

    it("filters themes by query", () => {
      const purple = filterThemes({ query: "purple" }, ROSTER).map((t) => t.id);
      expect(purple).toContain("nocturne");

      const importedOnes = filterThemes({ query: "imported" }, ROSTER).map((t) => t.id);
      expect(importedOnes).toContain("dracula");
    });

    it("filters themes by appearance and kind", () => {
      const light = filterThemes({ appearance: "light" }, ROSTER);
      expect(light.every((t) => t.schemes.includes("light"))).toBe(true);

      const adaptive = filterThemes({ kind: "adaptive" }, ROSTER);
      expect(adaptive.every((t) => t.kind === "adaptive")).toBe(true);
    });

    // Every adaptive theme leads with light but ships dark too; filtering on
    // the leading appearance alone would hide all of them here.
    it("counts an adaptive theme as both light and dark", () => {
      const dark = filterThemes({ appearance: "dark" }, ROSTER).map((t) => t.id);
      expect(dark).toContain("nocturne");
      expect(dark).toContain("kone");
    });
  });

  describe("tool execution & registry dispatch", () => {
    it("app_get_theme_state reports the appearance the renderer is painting", async () => {
      const reading: AppearanceReading = {
        themeId: "press",
        themeLabel: "Press",
        mode: "system",
        scheme: "dark",
        locked: true,
      };
      const registry = createRegistry(rosterTools({ readAppearance: () => reading }));

      const res = await registry.call(makeCtx(), "app_get_theme_state", {});
      expect(res.isError).toBeUndefined();

      // SAFETY: the tool's structuredContent is the CurrentThemeState it built.
      const structured = res.structuredContent as CurrentThemeState;
      expect(structured.known).toBe(true);
      expect(structured.themeId).toBe("press");
      expect(structured.resolvedScheme).toBe("dark");
      expect(structured.isLocked).toBe(true);
      expect(structured.accent).toBe("#ef6398");
      expect(structured.origin).toBe("built-in");
    });

    // The palette of an imported theme is unknowable here without the roster —
    // which is exactly what the roster supplies.
    it("app_get_theme_state describes an imported theme as fully as a built-in", async () => {
      const registry = createRegistry(
        rosterTools({
          readAppearance: () => ({
            themeId: "dracula",
            themeLabel: "Dracula",
            mode: "dark",
            scheme: "dark",
            locked: true,
          }),
        }),
      );

      const res = await registry.call(makeCtx(), "app_get_theme_state", {});
      // SAFETY: the tool's structuredContent is the CurrentThemeState it built.
      const structured = res.structuredContent as CurrentThemeState;
      expect(structured.origin).toBe("imported");
      expect(structured.accent).toBe("#bd93f9");
    });

    // Naming a default here would have the agent confidently describe a theme
    // the user is not looking at.
    it("app_get_theme_state says the theme is unknown before the renderer reports one", async () => {
      const registry = createRegistry(createAppThemeTools({}));

      const res = await registry.call(makeCtx(), "app_get_theme_state", {});
      // SAFETY: the tool's structuredContent is the CurrentThemeState it built.
      const structured = res.structuredContent as CurrentThemeState;
      expect(structured.known).toBe(false);
      expect(structured.themeId).toBeNull();
      expect(res.content[0]?.text).toContain("has not reported an appearance");
    });

    it("app_list_available_themes lists what the renderer reported", async () => {
      const registry = createRegistry(rosterTools());

      const res = await registry.call(makeCtx(), "app_list_available_themes", { query: "dark" });
      expect(res.isError).toBeUndefined();

      // SAFETY: shape asserted by app_list_available_themes' own return statement.
      const structured = res.structuredContent as { total: number; themes: Array<{ id: string }> };
      expect(structured.total).toBeGreaterThan(0);
      expect(structured.themes.some((t) => t.id === "nocturne")).toBe(true);
    });

    // The list an install actually holds is the built-ins plus whatever the
    // user imported or made, and only the renderer knows that set.
    it("app_list_available_themes offers imported and custom themes alongside the shipped ones", async () => {
      const registry = createRegistry(rosterTools());

      const res = await registry.call(makeCtx(), "app_list_available_themes", {});
      // SAFETY: shape asserted by app_list_available_themes' own return statement.
      const structured = res.structuredContent as { themes: Array<{ id: string; origin: string }> };
      const origins = new Set(structured.themes.map((t) => t.origin));
      expect(origins).toEqual(new Set(["built-in", "imported", "custom"]));
    });

    // Claiming an empty library would read as "kone has no themes" rather than
    // "kone has not said yet".
    it("app_list_available_themes says the library is unreported rather than empty", async () => {
      const registry = createRegistry(createAppThemeTools({}));

      const res = await registry.call(makeCtx(), "app_list_available_themes", {});
      expect(res.isError).toBeUndefined();
      // SAFETY: shape asserted by app_list_available_themes' own return statement.
      const structured = res.structuredContent as { known: boolean; total: number };
      expect(structured.known).toBe(false);
      expect(structured.total).toBe(0);
      expect(res.content[0]?.text).toContain("has not reported its theme library");
    });

    it("app_set_theme applies a valid theme and emits app.theme_mutation", async () => {
      const emitted: RuntimeEvent[] = [];
      const registry = createRegistry(rosterTools({ emit: (e) => emitted.push(e) }));

      const res = await registry.call(
        makeCtx({ threadId: "thread-xyz" }),
        "app_set_theme",
        { themeId: "nocturne", mode: "dark" },
      );

      expect(res.isError).toBeUndefined();
      // SAFETY: shape asserted by app_set_theme's own return statement.
      const structured = res.structuredContent as {
        ok: boolean;
        applied: { themeId: string; mode: string };
        previousState: { known: boolean };
      };

      expect(structured.ok).toBe(true);
      expect(structured.applied.themeId).toBe("nocturne");
      expect(structured.applied.mode).toBe("dark");
      expect(structured.previousState).toBeDefined();

      expect(emitted.length).toBe(1);
      expect(emitted[0]?.type).toBe("app.theme_mutation");
      if (emitted[0]?.type === "app.theme_mutation") {
        expect(emitted[0].themeId).toBe("nocturne");
        expect(emitted[0].mode).toBe("dark");
        expect(emitted[0].threadId).toBe("thread-xyz");
      }
    });

    // A theme the agent made itself has to be re-applicable by name afterwards.
    it("app_set_theme applies a custom theme the library reported", async () => {
      const emitted: RuntimeEvent[] = [];
      const registry = createRegistry(rosterTools({ emit: (e) => emitted.push(e) }));

      const res = await registry.call(makeCtx(), "app_set_theme", { themeId: "brand-indigo" });
      expect(res.isError).toBeUndefined();
      if (emitted[0]?.type === "app.theme_mutation") {
        expect(emitted[0].themeId).toBe("brand-indigo");
      }
    });

    it("app_set_theme returns an error on a theme the library does not hold", async () => {
      const emitted: RuntimeEvent[] = [];
      const registry = createRegistry(rosterTools({ emit: (e) => emitted.push(e) }));

      const res = await registry.call(makeCtx(), "app_set_theme", { themeId: "nonexistent-fantasy-theme" });
      expect(res.isError).toBe(true);
      expect(res.content[0]?.text).toContain('Unknown theme "nonexistent-fantasy-theme"');
      expect(emitted.length).toBe(0);
    });

    // Applying the nearest look-alike under a borrowed name would report
    // success for a theme the user never asked for and cannot see.
    it("app_set_theme refuses an outside theme name instead of substituting one", async () => {
      const roster = ROSTER.filter((t) => t.id !== "dracula");
      const registry = createRegistry(createAppThemeTools({ readThemes: () => roster }));

      const res = await registry.call(makeCtx(), "app_set_theme", { themeId: "dracula" });
      expect(res.isError).toBe(true);
      expect(res.content[0]?.text).toContain("import");
    });

    // Resolving a name against a library nobody has described yet could only
    // be a guess, and the guess would be reported as applied.
    it("app_set_theme refuses to resolve a name before the library is reported", async () => {
      const emitted: RuntimeEvent[] = [];
      const registry = createRegistry(createAppThemeTools({ emit: (e) => emitted.push(e) }));

      const res = await registry.call(makeCtx(), "app_set_theme", { themeId: "nocturne" });
      expect(res.isError).toBe(true);
      expect(res.content[0]?.text).toContain("has not reported its theme library");
      expect(emitted.length).toBe(0);
    });

    it("app_preview_theme_override emits preview events", async () => {
      const emitted: RuntimeEvent[] = [];
      const registry = createRegistry(rosterTools({ emit: (e) => emitted.push(e) }));

      const res = await registry.call(
        makeCtx(),
        "app_preview_theme_override",
        { themeId: "green", colors: { accent: "#38bdf8" } },
      );

      expect(res.isError).toBeUndefined();
      expect(emitted.length).toBe(1);
      expect(emitted[0]?.type).toBe("app.theme_mutation");
      if (emitted[0]?.type === "app.theme_mutation") {
        expect(emitted[0].preview).toBe(true);
        // Resolved to a real theme before emitting, not forwarded raw.
        expect(emitted[0].themeId).toBe("grove");
        expect(emitted[0].colors?.accent).toBe("#38bdf8");
      }

      const cancelRes = await registry.call(makeCtx(), "app_preview_theme_override", { cancel: true });
      expect(cancelRes.isError).toBeUndefined();
      expect(emitted.length).toBe(2);
      if (emitted[1]?.type === "app.theme_mutation") {
        expect(emitted[1].preview).toBe(false);
      }
    });

    it("app_create_custom_theme validates and creates custom theme", async () => {
      const emitted: RuntimeEvent[] = [];
      const registry = createRegistry(rosterTools({ emit: (e) => emitted.push(e) }));

      const res = await registry.call(
        makeCtx(),
        "app_create_custom_theme",
        {
          id: "brand-cobalt",
          label: "Brand Cobalt",
          appearance: "dark",
          accent: "#6366f1",
          ground: "#0f172a",
          roles: { panel: "#1e293b" },
        },
      );

      expect(res.isError).toBeUndefined();
      expect(emitted.length).toBe(1);
      expect(emitted[0]?.type).toBe("app.theme_mutation");
      if (emitted[0]?.type === "app.theme_mutation") {
        expect(emitted[0].themeId).toBe("brand-cobalt");
        expect(emitted[0].customTheme?.label).toBe("Brand Cobalt");
        expect(emitted[0].customTheme?.accent).toBe("#6366f1");
      }
    });

    // A dot is not a legal tool-name character for every client, so the dotted
    // form was dropped rather than registered alongside an alias.
    it("registers exactly one name per tool, in the underscore form", () => {
      const names = createAppThemeTools({}).map((t) => t.name);
      expect(names).toEqual([
        "app_get_theme_state",
        "app_list_available_themes",
        "app_set_theme",
        "app_preview_theme_override",
        "app_create_custom_theme",
      ]);
      expect(names.every((n) => /^[a-zA-Z0-9_-]+$/.test(n))).toBe(true);
    });

    it("app_preview_theme_override rejects a theme that does not exist", async () => {
      const emitted: RuntimeEvent[] = [];
      const registry = createRegistry(rosterTools({ emit: (e) => emitted.push(e) }));

      const res = await registry.call(makeCtx(), "app_preview_theme_override", {
        themeId: "nonexistent-fantasy-theme",
      });
      expect(res.isError).toBe(true);
      expect(emitted.length).toBe(0);
    });

    // A mode change names no theme, so it has nothing to look up and must work
    // whether or not the library has been reported.
    it("app_set_theme accepts a bare mode change and leaves the theme alone", async () => {
      const emitted: RuntimeEvent[] = [];
      const registry = createRegistry(createAppThemeTools({ emit: (e) => emitted.push(e) }));

      const res = await registry.call(makeCtx(), "app_set_theme", { mode: "light" });
      expect(res.isError).toBeUndefined();
      expect(emitted.length).toBe(1);
      if (emitted[0]?.type === "app.theme_mutation") {
        expect(emitted[0].mode).toBe("light");
        expect(emitted[0].themeId).toBeUndefined();
      }
    });

    it("automatically extracts mode when attached in themeId query (e.g. 'grove dark')", async () => {
      const emitted: RuntimeEvent[] = [];
      const registry = createRegistry(rosterTools({ emit: (e) => emitted.push(e) }));

      const setRes = await registry.call(makeCtx(), "app_set_theme", { theme: "grove dark" });
      expect(setRes.isError).toBeUndefined();
      // SAFETY: shape asserted by app_set_theme's own return statement.
      const structured = setRes.structuredContent as { applied: { themeId: string; mode: string } };
      expect(structured.applied.themeId).toBe("grove");
      expect(structured.applied.mode).toBe("dark");
    });
  });
});
